// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  background_image: dynamic(() => import("./BackgroundImage")),
  image_section: dynamic(() => import("./ImageSection")),
};
